n = input('Digite algo: ')
print('{0} é um {1}'.format(n, type(n)))
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isnumeric())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())
